// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kntaewyrskhlhvgsukwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudGFld3lyc2tobGh2Z3N1a3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjU2OTIsImV4cCI6MjA2MzkwMTY5Mn0.RrUEi1WnskN_YfvCbR7hUtjQGQFJec62Ph0ssaZuN44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);